---
title: 'Analysis Report'
output:
  prettydoc::html_pretty:
    theme: architect
    mathjax: null
    css: "style.css"

keep_md: true
always_allow_html: true
self_contained: true

params:
  argosDir : "~/Work/mutation_report_sample_level/data/argos/08390_R/1.1.2/20230208_22_12_784560"
  sampleID : "s_C_8XFJMJ_P001_d01"
  geneAnnotation_path : dummy
---

```{r loadData, echo=FALSE, include=FALSE}
source("load_data.R", local=knitr::knit_global())
data=load_data(params$argosDir,params$sampleID)
```


```{r, echo=FALSE}
htmltools::img(src = "MSKCC-logo.png",
               alt = 'logo',
               class = 'img_class',
               style = 'position:absolute; top:-120px; left:0; padding:3px; max-height: 40px', 
               # width = "30%",
               heigth = "auto"
               )
```

```{r set_defaults, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = NA)
```

```{r data_clinical, echo=FALSE}
clinical_header_row_css<- "background-color: #737373; color: #fff;"
clinical_col_css<- "text-align: right; padding-right: 0.5em;"
kable(data$tbl01, col.names = NULL) %>% 
  kable_styling(htmltable_class = "data_clinical_table_style", full_width = T, position = "left") %>% 
  add_header_above(c( "Data clinical:" = 4), align= "l",extra_css= clinical_header_row_css )%>%
  column_spec(1, width = "7em", bold = TRUE, extra_css=clinical_col_css) %>%
  column_spec(2, width = "1em") %>%
  column_spec(3, width = "1em", bold = TRUE, extra_css=clinical_col_css) %>%
  column_spec(4, width = "7em")
```

```{r summary, echo=FALSE}
kable(data$summaryTbl, col.names = NULL) %>% 
  kable_styling(htmltable_class = "summary_table_style", full_width = T, position = "left") %>% 
  column_spec(1, width = "6em", bold = TRUE)
```
<!---
Collapsibles: https://www.digitalocean.com/community/tutorials/css-collapsible
-->
```{=html}
<div class="wrap-collabsible"> 
    <input id="collapsible_mafTbl" class="toggle" type="checkbox" checked> 
    
    <label for="collapsible_mafTbl" class="lbl-toggle">
        Somatic alterations detected in this sample:
    </label>

    <div class="collapsible-content">     
        <div class="content-inner">  
```
```{r mutations, echo=FALSE}
row_middle_css <- "background-color: #9BDCFF; color: #fff;"
n <- rbind(data$mafTbl,data$cnvTbl,data$fusionTbl)

kable(n, escape = FALSE) %>% kable_styling( full_width = T, position = "left")%>%
  pack_rows("Mutations", 1, nrow(data$mafTbl), label_row_css = row_middle_css)%>%
  pack_rows("Copy Number Alterations", nrow(data$mafTbl)+1, nrow(data$mafTbl)+nrow(data$cnvTbl), label_row_css = row_middle_css) %>%
  pack_rows("Fusion events", nrow(data$mafTbl)+nrow(data$cnvTbl)+1, nrow(data$mafTbl)+nrow(data$cnvTbl)+nrow(data$fusionTbl), label_row_css = row_middle_css)
```
```{=html}
</div>
</div>
</div>
```

```{r methods, echo=FALSE}
free_text_header_css <- "background-color: #FFBE19; padding-left: 0px; color: #fff; "

kable(data$methods, col.names = NULL, align = "lc", escape = FALSE)%>%
  kable_styling(htmltable_class = "methods_table_style", full_width = T, position = "left") %>% 
  add_header_above(c( "Methods:" = 1), align= "l",extra_css= free_text_header_css ) %>%
  row_spec(1, extra_css = "text-align: justify; background-color: #fff;")

#font-size:2vw;
#htmltable_class = "table_class",
```

```{r glossary, echo=FALSE}
kable(data$glossaryTbl, escape = FALSE)%>%
  kable_styling(htmltable_class = "summary_table_style", full_width = T, position = "left") %>% 
  add_header_above(c("Glossary of terms used in the report" = 2), align= "l",extra_css= free_text_header_css )
```


---

```{=html}
<div class="wrap-collabsible"> 
    <input id="collapsible_mafTblFull" class="toggle" type="checkbox"> 
    
    <label for="collapsible_mafTblFull" class="lbl-toggle">
        Unfiltered set of mutations:
    </label>

    <div class="collapsible-content">     
        <div class="content-inner">  
```

```{r unfiltered_mutations, echo=FALSE}
kable(data$mafTblFull, escape = FALSE)
```
```{=html}
</div>
</div>
</div>
```

```{=html}
<div class="wrap-collabsible"> 
    <input id="collapsible_cnvTblFull" class="toggle" type="checkbox"> 
    
    <label for="collapsible_cnvTblFull" class="lbl-toggle">
       Unfiltered set of copy number alterations:
    </label>

    <div class="collapsible-content">     
        <div class="content-inner">
```
```{r unfiltered_cnvs, echo=FALSE}
kable(data$cnvTblFull, escape = FALSE)
```
```{=html}
</div>
</div>
</div>
```



```{r report_info, echo=FALSE}
kable(data$reportTbl, col.names = NULL) %>% 
  kable_styling(htmltable_class = "report_info_table_class", full_width = F, position = "left")%>% 
  column_spec(1, bold = T)
```
