---
title: 'Analysis Report'
output:
  prettydoc::html_pretty:
    theme: architect
    mathjax: null
    css: "style.css"

keep_md: true
always_allow_html: true
self_contained: true

params:
  argosDir : "~/Work/mutation_report_sample_level/data/argos/11704_Y/1.1.2/20221102_20_40_060423"
  sampleID : "s_C_VXXWFY_X006_d05"
  #geneAnnotation_path : dummy
---



```{r loadData, echo=FALSE, include=FALSE}
source("load_data.R", local=knitr::knit_global())
data=load_data(params$argosDir,params$sampleID)
```

<!-- folding sections -->
```{r, echo=FALSE, include=TRUE}
htmltools::tagList(
  htmltools::tags$script(src="https://code.jquery.com/jquery-3.2.1.min.js"),
  htmltools::tags$script(src="dist/jquery-folding-arrow-icon-min.js"),
  htmltools::tags$link(href="dist/jquery-folding-arrow-icon.css", rel="stylesheet")
)
```
```{css, echo=FALSE}
 h2.folding-arrow .folding-arrow-icon path {
            stroke: navy;
            stroke-width: 2;
            fill: none;
        }
        h2.sec {
            border: 1px solid silver;
            background-color: #eee;
            border-radius: 0.3em;
            padding: 0.2em;
            margin-top: 0;
        }
        
        h2.sec a, h2.sec a:link, h2.sec a:visited {
            text-decoration: none;
            color: #007;
        }
        
        h2.folding-arrow + div > :first-child {
            margin-top: 0;
        }
        h2.folding-arrow + div > :last-child {
            margin-bottom: 0;
        }
        h2.folding-arrow + div {
            margin-bottom: 2em;
        }  
```
```{js, echo = FALSE}

        $(function(){
            
            function registerSectionClickHandler(section) {
                section.click(function() {
                    openOrCloseSection(section)
                }).children("a").first().click(function(ev) {
                    ev.preventDefault();
                    ev.stopPropagation();
                    openOrCloseSection(section);
                });
            }
            
            registerSectionClickHandler(
                $("#sec-prefix").prependFoldingArrowIcon({
                    closePath: false
                }).setupFoldingArrowIconTransformation()
            );
                             
            $("h2.sec").each(function() {
                $(this).next().hide();
            }).setupFoldingArrowIconTransformation({
                titleHidden: "open section"
            });

            
        });
        
        function openOrClose(jqr) {
            return jqr.toggleClass("showing").transformFoldingArrowIcon();
        }
        
        function openOrCloseLi(li) {
            openOrClose(li);
            if (li.is(".showing"))
                $("ul", li).slideDown(500);
            else
                $("ul", li).slideUp(500);
        }
        
        function openOrCloseSection(h) {
            if (!h.is(".showing")) {
                //collapse currently open section(s):
                $("h2.sec.showing").each(function() {
                    openOrCloseSection($(this));
                });
                openOrClose(h);
                h.next().slideDown(500);
            } else {
                openOrClose(h);
                h.next().slideUp(500);
            }
        }
```
<!-- END of folding sections -->



```{css, echo=FALSE}
@media screen and (max-width: 600px) {
  img.img_class {
    display: none;
  }
}
```
```{r, echo=FALSE}
htmltools::img(src = "MSKCC-logo.png",
               alt = 'logo',
               class = 'img_class',
               style = 'position:absolute; top:-90px; left:0; padding:3px; max-height: 40px', 
               # width = "30%",
               heigth = "auto"
               )
```

```{r set_defaults, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = NA)
```













```{r data_clinical, echo=FALSE}
clinical_header_row_css<- "background-color: #8b8da3; color: #fff;"
kable(data$tbl01, col.names = NULL) %>% kable_styling(htmltable_class = "data_clinical_table_style", full_width = T, position = "left") %>% add_header_above(c( "Data clinical:" = 4), align= "l",extra_css= clinical_header_row_css )
```

```{r summary, echo=FALSE}
kable(data$summaryTbl, col.names = NULL) %>% kable_styling(htmltable_class = "summary_table_style", full_width = T, position = "left") %>% column_spec(1, bold = T)
```


```{r mutations, echo=FALSE}
row_top_css <- "background-color: #63a0e1; color: #fff;"
row_middle_css <- "background-color: #87CEFA; color: #fff;"
n <- rbind(data$mafTbl,data$cnvTbl,data$fusionTbl)

kable(n) %>% kable_styling(htmltable_class = "table_class", full_width = T, position = "left")%>%
  add_header_above(c( "Somatic alterations detected in this sample:" = 5), align= "l",extra_css= row_top_css )%>%
  pack_rows("Mutations", 1, nrow(data$mafTbl), label_row_css = row_middle_css)%>%
  pack_rows("Copy Number Alterations", nrow(data$mafTbl)+1, nrow(data$mafTbl)+nrow(data$cnvTbl), label_row_css = row_middle_css) %>%
  pack_rows("Fusion events", nrow(data$mafTbl)+nrow(data$cnvTbl)+1, nrow(data$mafTbl)+nrow(data$cnvTbl)+nrow(data$fusionTbl), label_row_css = row_middle_css)
```

```{=html}
<h2 class="sec" id="sec-prefix" style="font-size: 12px;" ><a href="#!">Unfiltered set of Copy Number Alterations:</a></h2>
<div>    
```

```{r cnvs, echo=FALSE}
kable(data$cnvTblFull)%>%
  add_header_above(c( "Unfiltered set of Copy Number Alterations:" = 5), align= "l",extra_css= row_top_css )
```

```{=html}
</div>
```


```{r report_info, echo=FALSE}
kable(data$reportTbl, col.names = NULL) %>% 
  kable_styling( full_width = F, position = "left")%>% 
  column_spec(1, bold = T)
```

