name: base
channels:
  - conda-forge
  - r
dependencies:
  - r=4.1
  - r-base=4.1.0
  - r-argparse=2.0.4
  - r-ggplot2=3.3.5
  - r-rmarkdown=2.10
  - r-reshape2=1.4.4
  - pandoc=2.14.2
  - r-knitr=1.33
  - r-dt=0.18
  - r-plotly=4.9.4.1
  - r-data.table=1.14.0
